app.config(['$translateProvider', function ($translateProvider) {
    $translateProvider.translations('en', {
        label_home: 'home',
        label_profile: 'profile',
        label_service: 'services',
        label_resume: 'Resume',
        label_contact: 'contact',
        label_skill: 'Skills',
        label_welcome: "Hello, I'm Lucas Vieira",
        label_developer: ".NET Developer",
        label_web_developer: "Web developer",
        label_windows_developer: "Windows Application Developer",
        database: "Database",
        methodology: "Methodology",
        label_social_profiles: 'Social Profiles',
        label_professional_profile: 'Profesional Profile',
        text_professional_profile_1: 'Experience in software development using technologies: <strong>SOA, Rest, C#, Asp.Net Web Forms, Asp.Net MVC, Entity Framework, Java, Hibernate, SQL Server, Oracle PL/SQL, MySql, AngularJs, HTML5, CSS3, WebSocket, SignalR, JavaScript, jQuery, Bootstrap, Grunt, Bower.</strong><br><br>Experience with versioning and system life cycle using <strong>TFS - Team Foundation Server.</strong><br><br> Reviews of code to improve performance, security, speed, cleanliness, standardization and documentation.',
        label_what_i_can_do: 'What i can do',
        label_my_services: 'My Services.',
        label_aspnet_solutions: 'Web Sites Asp.Net',
        text_aspnet_solutions: 'Great build sites and web applications using HTML, CSS and JavaScript!',
        label_webapi: 'Web API\'s',
        text_webapi: 'Build HTTP services that reach a wide range of clients including browsers and mobile devices.',
        label_windows_application: 'Windows Application',
        text_windows_application: 'Build programs for Windows and applications to the Windows Store.',
        label_database: 'Database',
        text_database: 'Use the database that best suits your need Microsoft SQLServer, Oracle or MySQL.',
        label_angularJs: 'Web Sites AngularJs',
        text_angularJs: 'Build your web sites using this incredible Javascript framework, ideal for those who want speed without losing quality.',
        label_resume_subtitle: 'My education and experience.',
        label_education: 'Education',
        name_analysis_and_systems_development: 'Analysis and Systems development',
        descriptin_analysis_and_systems_development: 'The course includes the study of several existing systems of hardware, software and the end user, for the student to understand their behaviors and applications. This training is presented as an excellent alternative and meets with a labor market expanding and in need of professionals with solid technical and academic training.',
        place_analysis_and_systems_development: 'Anhanguera Univercity',
        label_experience: 'Experience',
        name_experience_trainee: 'Trainee .NET Development',
        description_experience_trainne: 'In this period had experiences in web major customers such as Carrefour and Kroton systems, this could work in several activities such as documentation, quality testing, development features. I could also join Oracle training and .NET.',
        place_experience_trainne: 'ST IT Consulting',
        name_experience_programmer_analyst_jr: 'Programmer Analyst Jr.',
        description_experience_programmer_analyst_jr: 'During this period I worked with more complex tasks in the development of Web systems, assist and monitor all stages of the project, requirements gathering, technical survey, development, approval and implementation in production. I deepened my knowledge by working with more experienced developers.',
        currently: 'Currently',
        name_experience_programmer_analyst_full: 'Programmer Analyst Full',
        description_experience_programmer_analyst_full: 'In this role I could perform with Web systems development and desktop , the Web development projects that participated had experience with the following technologies: Arquitetura SOA, .NET, Java, Entity Framework, Hibernate, Web Api, AngularJs, Bootstrap, HTML5, CSS3, JavaScript, jQuery, Asp.net MVC.',
        label_contact_us: 'Contact Me',
        all_rights_reserved: 'All Rights Reserved.',
        label_name: 'Name',
        placeholder_message: 'Enter your message here',
        error_message_required: 'This field is required',
        button_sending: 'Sending...',
        button_send: 'Send',
        label_contact_subtitle: 'Liked my qualifications please contact me !',
        error_send_message: 'Error sending e-mail',
        sucess_send_message: 'Email sent successfully',
        certification_label: 'Certificates',
        certification_csharp_programming: 'MS: Programming in C#',
        certification_csharp_organ_issuer: 'Microsoft',
    });
}]);