app.config(['$translateProvider', function ($translateProvider) {
    $translateProvider.translations('pt-BR', {
        label_home: 'inicio',
        label_profile: 'perfil',
        label_service: 'serviços',
        label_resume: 'Resumo',
        label_contact: 'contato',
        label_skill: 'Habilidades',
        label_welcome: "Olá, Eu sou Lucas Vieira",
        label_developer: "Desenvolvedor .NET",
        label_web_developer: "Desenvolvedor Web",
        label_windows_developer: "Desenvolvedor de Aplicações Windows",
        database: "Banco de Dados",
        methodology: "Metodologia",
        label_social_profiles: 'Perfis Sociais',
        label_professional_profile: 'Perfil Profissional',
        text_professional_profile_1: 'Experiencia em desenvolvimento de software utilizando as tecnologias: <strong>SOA, Rest, C#, Asp.Net Web Forms, Asp.Net MVC, Entity Framework, Java, Hibernate, SQL Server, Oracle PL/SQL, MySql, AngularJs, HTML5, CSS3, WebSocket, SignalR, JavaScript, jQuery, Bootstrap, Grunt, Bower.</strong><br><br>Experiência com versionamento e ciclo de vida do sistema utilizando <strong>TFS - Team Foundation Server.</strong><br><br>Revisões de código para o melhoramento de performance, segurança, velocidade, limpeza, padronização e documentação.',
        label_what_i_can_do: 'O que eu posso fazer',
        label_my_services: 'Meus Serviços.',
        label_aspnet_solutions: 'Web Sites Asp.Net',
        text_aspnet_solutions: 'Construa grandes web sites e aplicações web utilizando HTML, CSS e JavaScript!',
        label_webapi: 'Web API\'s',
        text_webapi: 'Construa serviços HTTP que chegam a uma ampla gama de clientes, incluindo navegadores e dispositivos móveis.',
        label_windows_application: 'Aplicativos Windows',
        text_windows_application: 'Construa programas para Windows e aplicativos para a Windows Store.',
        label_database: 'Banco de Dados',
        text_database: 'Utilize o banco de dados que se adapte melhor a sua necessidade Microsoft SQLServer, Oracle ou MySql.',
        label_angularJs: 'Web Sites AngularJs',
        text_angularJs: 'Construa seus web sites utilizando esse incrivel framework de Javascript, ideal para quem quer velocidade sem perder qualidade.',
        label_resume_subtitle: 'Minha educação e experiência.',
        label_education: 'Educação',
        name_analysis_and_systems_development: 'Análise e Desenvolvimento de Sistemas',
        descriptin_analysis_and_systems_development: 'O curso contempla o estudo de diversos sistemas existentes entre hardwares, softwares e o usuário final, para que o estudante compreenda seus comportamentos e aplicações. Essa formação profissional apresenta-se como excelente alternativa e vai de encontro com um mercado de trabalho em expansão e carente de profissionais com sólida formação técnica e acadêmica.',
        place_analysis_and_systems_development: 'Universidade Anhanguera',
        label_experience: 'Experiências',
        name_experience_trainee: 'Estágiario em Desenvolvimento .NET',
        description_experience_trainne: 'Neste período tive vivencia em sistemas Web de grandes clientes como Carrefour e Kroton, neste pude atuar em diversas atividades como documentação, teste de qualidade, desenvolvimento de funcionalidades. Também pude participar de treinamentos de Oracle e .NET.',
        place_experience_trainne: 'ST IT Consulting',
        name_experience_programmer_analyst_jr: 'Analista Programador Jr',
        description_experience_programmer_analyst_jr: 'Neste período atuei com tarefas mais complexas no desenvolvimento de sistemas Web, auxiliar e acompanhar todas as etapas do projeto, levantamento de requisitos, levantamento técnico, desenvolvimento, homologação e implantação em produção. Aprofundei meus conhecimentos trabalhando com outros desenvolvedores mais experientes.',
        currently: 'Atualmente',
        name_experience_programmer_analyst_full: 'Analista Programador Pleno',
        description_experience_programmer_analyst_full: 'Neste cargo pude atuar com desenvolvimento de Sistemas Web e desktop, nos projetos de desenvolvimento Web que participei tive experiência com as seguintes tecnologias: Arquitetura SOA, .NET, Java, Entity Framework, Hibernate, Web Api, AngularJs, Bootstrap, HTML5, CSS3, JavaScript, jQuery, Asp.net MVC.',
        label_contact_us: 'Contate Me',
        all_rights_reserved: 'Todos os direitos reservados.',
        label_name: 'Nome',
        placeholder_message: 'Digite aqui sua mensagem',
        error_message_required: 'Esse campo é obrigátorio',
        button_sending: 'Enviando...',
        button_send: 'Enviar',
        label_contact_subtitle: 'Gostou das minhas qualificações entre em contato comigo!',
        error_send_message: 'Error ao enviar o e-mail',
        sucess_send_message: 'E-mail enviado com sucesso!',
        certification_label: 'Certificados',
        certification_csharp_programming: 'MS: Programming in C#',
        certification_csharp_organ_issuer: 'Microsoft',

    });
}]);